"""llm reports

Revision ID: 20260730_0003
Revises: 20260729_0002
Create Date: 2026-07-29 11:14:12.805817+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260730_0003'
down_revision: Union[str, None] = '20260729_0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_report_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cadence', sa.String(length=10), server_default='off', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cadence IN ('off', 'weekly', 'monthly')", name='ck_llm_report_schedules_cadence'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_llm_report_schedules_user')
    )
    op.create_index(op.f('ix_llm_report_schedules_id'), 'llm_report_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_llm_report_schedules_user_id'), 'llm_report_schedules', ['user_id'], unique=False)
    op.create_table('llm_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('trigger_source', sa.String(length=20), nullable=False),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("trigger_source IN ('manual', 'scheduled')", name='ck_llm_reports_trigger_source'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_reports_id'), 'llm_reports', ['id'], unique=False)
    op.create_index('ix_llm_reports_user_created', 'llm_reports', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_llm_reports_user_id'), 'llm_reports', ['user_id'], unique=False)
    op.create_table('llm_report_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_llm_report_messages_role'),
    sa.ForeignKeyConstraint(['report_id'], ['llm_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_report_messages_id'), 'llm_report_messages', ['id'], unique=False)
    op.create_index('ix_llm_report_messages_report', 'llm_report_messages', ['report_id', 'id'], unique=False)
    op.create_index(op.f('ix_llm_report_messages_report_id'), 'llm_report_messages', ['report_id'], unique=False)
    op.create_index(op.f('ix_llm_report_messages_user_id'), 'llm_report_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_llm_report_messages_user_id'), table_name='llm_report_messages')
    op.drop_index(op.f('ix_llm_report_messages_report_id'), table_name='llm_report_messages')
    op.drop_index('ix_llm_report_messages_report', table_name='llm_report_messages')
    op.drop_index(op.f('ix_llm_report_messages_id'), table_name='llm_report_messages')
    op.drop_table('llm_report_messages')
    op.drop_index(op.f('ix_llm_reports_user_id'), table_name='llm_reports')
    op.drop_index('ix_llm_reports_user_created', table_name='llm_reports')
    op.drop_index(op.f('ix_llm_reports_id'), table_name='llm_reports')
    op.drop_table('llm_reports')
    op.drop_index(op.f('ix_llm_report_schedules_user_id'), table_name='llm_report_schedules')
    op.drop_index(op.f('ix_llm_report_schedules_id'), table_name='llm_report_schedules')
    op.drop_table('llm_report_schedules')
    # ### end Alembic commands ###
