"""security profile data and analyses

Revision ID: 20260802_0007
Revises: 20260801_0006
Create Date: 2026-08-02 08:59:50.623122+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260802_0007'
down_revision: Union[str, None] = '20260801_0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='资产名称'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='结构化标签数组'),
    sa.Column('risk_level', sa.String(length=10), nullable=False, comment='low / medium / high'),
    sa.Column('summary', sa.String(length=300), nullable=False, comment='一句话摘要'),
    sa.Column('content', sa.Text(), nullable=False, comment='Markdown 全文分析'),
    sa.Column('model', sa.String(length=50), nullable=False, comment='生成模型'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False, comment='生成时的压缩输入（可复现）'),
    sa.Column('data_fetched_at', sa.Date(), nullable=True, comment='输入数据抓取日（非数据截止日：数据本身的报告期见各数据集 period）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high')", name='ck_security_analyses_risk_level'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_analyses_id'), 'security_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_security_analyses_symbol'), 'security_analyses', ['symbol'], unique=False)
    op.create_table('security_profile_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场'),
    sa.Column('dataset', sa.String(length=30), nullable=False, comment='数据集（Tushare 接口名）'),
    sa.Column('period_key', sa.String(length=40), nullable=False, comment='报告期/公告日等自然键'),
    sa.Column('payload', sa.JSON(), nullable=False, comment='原始行（归一后的 JSON）'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dataset IN ('fina_indicator', 'forecast', 'express', 'daily_basic', 'dividend_history', 'fina_audit', 'pledge_stat', 'stk_holdertrade')", name='ck_security_profile_dataset'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', 'dataset', 'period_key', name='uq_security_profile_identity')
    )
    op.create_index(op.f('ix_security_profile_data_id'), 'security_profile_data', ['id'], unique=False)
    op.create_index(op.f('ix_security_profile_data_symbol'), 'security_profile_data', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_profile_data_symbol'), table_name='security_profile_data')
    op.drop_index(op.f('ix_security_profile_data_id'), table_name='security_profile_data')
    op.drop_table('security_profile_data')
    op.drop_index(op.f('ix_security_analyses_symbol'), table_name='security_analyses')
    op.drop_index(op.f('ix_security_analyses_id'), table_name='security_analyses')
    op.drop_table('security_analyses')
    # ### end Alembic commands ###
