"""initial schema

Revision ID: 20260728_0001
Revises:
Create Date: 2026-07-28 01:19:52.096996+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260728_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_currency', sa.String(length=10), nullable=False),
    sa.Column('to_currency', sa.String(length=10), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_currency', 'to_currency', 'effective_date', name='uix_currency_date')
    )
    op.create_index(op.f('ix_exchange_rates_effective_date'), 'exchange_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_exchange_rates_from_currency'), 'exchange_rates', ['from_currency'], unique=False)
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_index(op.f('ix_exchange_rates_to_currency'), 'exchange_rates', ['to_currency'], unique=False)
    op.create_table('security_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('ts_code', sa.String(length=50), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('pre_close_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('adj_factor', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('adj_close_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', 'price_date', name='uix_security_price_symbol_market_date')
    )
    op.create_index(op.f('ix_security_prices_id'), 'security_prices', ['id'], unique=False)
    op.create_index(op.f('ix_security_prices_market'), 'security_prices', ['market'], unique=False)
    op.create_index(op.f('ix_security_prices_price_date'), 'security_prices', ['price_date'], unique=False)
    op.create_index(op.f('ix_security_prices_symbol'), 'security_prices', ['symbol'], unique=False)
    op.create_index(op.f('ix_security_prices_ts_code'), 'security_prices', ['ts_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auth_sessions_expires_at', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'interrupted')", name='ck_background_jobs_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_background_jobs_claim', 'background_jobs', ['status', 'next_attempt_at'], unique=False)
    op.create_index('ix_background_jobs_finished_at', 'background_jobs', ['finished_at'], unique=False)
    op.create_index('ix_background_jobs_user_type', 'background_jobs', ['user_id', 'job_type'], unique=False)
    op.create_index('uq_background_jobs_active_user_type', 'background_jobs', ['user_id', 'job_type'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.create_table('broker_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('account_number_masked', sa.String(length=100), nullable=True),
    sa.Column('base_currency', sa.String(length=10), server_default='CNY', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_accounts_broker'), 'broker_accounts', ['broker'], unique=False)
    op.create_index(op.f('ix_broker_accounts_id'), 'broker_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('cash_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='CNY', nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('DEPOSIT', 'WITHDRAWAL', 'INTEREST', 'FEE', 'TAX', 'TRANSFER_IN', 'TRANSFER_OUT', 'FX_IN', 'FX_OUT', 'OTHER')", name='ck_cash_events_type'),
    sa.CheckConstraint('amount > 0', name='ck_cash_events_positive_amount'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_events_broker_account_id'), 'cash_events', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_cash_events_currency'), 'cash_events', ['currency'], unique=False)
    op.create_index(op.f('ix_cash_events_event_date'), 'cash_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_cash_events_event_type'), 'cash_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_cash_events_id'), 'cash_events', ['id'], unique=False)
    op.create_index(op.f('ix_cash_events_user_id'), 'cash_events', ['user_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker_account_id', 'symbol', 'market', name='uix_user_account_symbol_market', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_holdings_broker_account_id'), 'holdings', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_market'), 'holdings', ['market'], unique=False)
    op.create_index(op.f('ix_holdings_symbol'), 'holdings', ['symbol'], unique=False)
    op.create_index(op.f('ix_holdings_user_id'), 'holdings', ['user_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('broker', sa.String(length=100), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('row_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('archived_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('duplicate_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=True),
    sa.Column('parser_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'COMPLETED', 'PARTIAL', 'FAILED')", name='ck_import_batches_status'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_broker'), 'import_batches', ['broker'], unique=False)
    op.create_index(op.f('ix_import_batches_broker_account_id'), 'import_batches', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_import_batches_id'), 'import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_import_batches_source_sha256'), 'import_batches', ['source_sha256'], unique=False)
    op.create_index(op.f('ix_import_batches_source_type'), 'import_batches', ['source_type'], unique=False)
    op.create_index(op.f('ix_import_batches_status'), 'import_batches', ['status'], unique=False)
    op.create_index(op.f('ix_import_batches_user_id'), 'import_batches', ['user_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='资产名称'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='行动类型'),
    sa.Column('ex_date', sa.Date(), nullable=False, comment='除权除息日'),
    sa.Column('record_date', sa.Date(), nullable=True, comment='登记日'),
    sa.Column('payment_date', sa.Date(), nullable=True, comment='支付日/到账日'),
    sa.Column('dividend_per_share', sa.Numeric(precision=18, scale=8), nullable=True, comment='每股股息金额'),
    sa.Column('total_dividend', sa.Numeric(precision=18, scale=8), nullable=True, comment='股息总额'),
    sa.Column('tax_withheld', sa.Numeric(precision=18, scale=8), nullable=True, comment='预扣税金额'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=True, comment='税率（如0.10表示10%）'),
    sa.Column('net_dividend', sa.Numeric(precision=18, scale=8), nullable=True, comment='税后净股息'),
    sa.Column('shares_received', sa.Numeric(precision=18, scale=8), nullable=True, comment='获得的股票数量'),
    sa.Column('distribution_ratio', sa.String(length=20), nullable=True, comment='分配比例（如10:3表示每10股送3股）'),
    sa.Column('subscription_price', sa.Numeric(precision=18, scale=8), nullable=True, comment='认购价格'),
    sa.Column('subscription_quantity', sa.Numeric(precision=18, scale=8), nullable=True, comment='认购数量'),
    sa.Column('subscription_amount', sa.Numeric(precision=18, scale=8), nullable=True, comment='认购金额'),
    sa.Column('split_ratio', sa.String(length=20), nullable=True, comment='拆股比例（如1:2表示1股拆2股）'),
    sa.Column('new_shares', sa.Numeric(precision=18, scale=8), nullable=True, comment='拆股后的股数'),
    sa.Column('cost_basis_adjustment', sa.Numeric(precision=18, scale=8), nullable=True, comment='成本基础调整金额'),
    sa.Column('adjusted_quantity', sa.Numeric(precision=18, scale=8), nullable=True, comment='调整后的持股数量'),
    sa.Column('adjusted_cost_per_share', sa.Numeric(precision=18, scale=8), nullable=True, comment='调整后的每股成本'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='币种'),
    sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_actions_action_type'), 'corporate_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_corporate_actions_broker_account_id'), 'corporate_actions', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_ex_date'), 'corporate_actions', ['ex_date'], unique=False)
    op.create_index(op.f('ix_corporate_actions_id'), 'corporate_actions', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_import_batch_id'), 'corporate_actions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_corporate_actions_market'), 'corporate_actions', ['market'], unique=False)
    op.create_index(op.f('ix_corporate_actions_symbol'), 'corporate_actions', ['symbol'], unique=False)
    op.create_index(op.f('ix_corporate_actions_user_id'), 'corporate_actions', ['user_id'], unique=False)
    op.create_table('reconciliation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('statement_scope', sa.String(length=30), nullable=True),
    sa.Column('cash_balances', sa.JSON(), nullable=False),
    sa.Column('positions', sa.JSON(), nullable=False),
    sa.Column('diff_detail', sa.JSON(), nullable=True),
    sa.Column('compared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('PENDING', 'MATCHED', 'MISMATCHED')", name='ck_reconciliation_snapshots_status'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_snapshots_broker_account_id'), 'reconciliation_snapshots', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_snapshots_id'), 'reconciliation_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_reconciliation_snapshots_import_batch_id'), 'reconciliation_snapshots', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_snapshots_snapshot_date'), 'reconciliation_snapshots', ['snapshot_date'], unique=False)
    op.create_index(op.f('ix_reconciliation_snapshots_status'), 'reconciliation_snapshots', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_snapshots_user_id'), 'reconciliation_snapshots', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('transaction_type', sa.String(length=20), nullable=False),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_broker_account_id'), 'transactions', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_import_batch_id'), 'transactions', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_transactions_linked_transaction_id'), 'transactions', ['linked_transaction_id'], unique=False)
    op.create_index(op.f('ix_transactions_market'), 'transactions', ['market'], unique=False)
    op.create_index(op.f('ix_transactions_symbol'), 'transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('broker_fund_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('corporate_action_id', sa.Integer(), nullable=True),
    sa.Column('cash_event_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('security_code', sa.String(length=20), nullable=True),
    sa.Column('security_name', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('trade_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('trade_quantity', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('remaining_quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('settlement_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('statement_type', sa.String(length=30), nullable=True),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('serial_number', sa.String(length=50), nullable=True),
    sa.Column('business_name', sa.String(length=50), nullable=False),
    sa.Column('stamp_tax', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('commission', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('handling_fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('management_fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('settlement_fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('transfer_fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('other_fee', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('shareholder_code', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cash_event_id'], ['cash_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['corporate_action_id'], ['corporate_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'broker_account_id', 'row_hash', name='uix_broker_flow_user_account_hash')
    )
    op.create_index(op.f('ix_broker_fund_flows_broker'), 'broker_fund_flows', ['broker'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_broker_account_id'), 'broker_fund_flows', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_business_name'), 'broker_fund_flows', ['business_name'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_cash_event_id'), 'broker_fund_flows', ['cash_event_id'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_corporate_action_id'), 'broker_fund_flows', ['corporate_action_id'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_id'), 'broker_fund_flows', ['id'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_import_batch_id'), 'broker_fund_flows', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_row_hash'), 'broker_fund_flows', ['row_hash'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_security_code'), 'broker_fund_flows', ['security_code'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_serial_number'), 'broker_fund_flows', ['serial_number'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_trade_date'), 'broker_fund_flows', ['trade_date'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_transaction_id'), 'broker_fund_flows', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_broker_fund_flows_user_id'), 'broker_fund_flows', ['user_id'], unique=False)
    op.create_index('uix_broker_flow_user_hash_unassigned', 'broker_fund_flows', ['user_id', 'row_hash'], unique=True, postgresql_where=sa.text('broker_account_id IS NULL'))
    op.create_table('ibkr_activity_flows',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('corporate_action_id', sa.Integer(), nullable=True),
    sa.Column('broker_account_id', sa.Integer(), nullable=True),
    sa.Column('import_batch_id', sa.Integer(), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=50), nullable=True),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('raw_symbol', sa.String(length=50), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('market', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('price_currency', sa.String(length=10), nullable=True),
    sa.Column('base_currency', sa.String(length=10), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('commission', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('net_amount', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('fee_in_price_currency', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('skip_reason', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['corporate_action_id'], ['corporate_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'row_hash', name='uix_ibkr_activity_user_hash')
    )
    op.create_index(op.f('ix_ibkr_activity_flows_activity_type'), 'ibkr_activity_flows', ['activity_type'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_broker'), 'ibkr_activity_flows', ['broker'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_broker_account_id'), 'ibkr_activity_flows', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_corporate_action_id'), 'ibkr_activity_flows', ['corporate_action_id'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_id'), 'ibkr_activity_flows', ['id'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_import_batch_id'), 'ibkr_activity_flows', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_market'), 'ibkr_activity_flows', ['market'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_raw_symbol'), 'ibkr_activity_flows', ['raw_symbol'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_row_hash'), 'ibkr_activity_flows', ['row_hash'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_symbol'), 'ibkr_activity_flows', ['symbol'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_trade_date'), 'ibkr_activity_flows', ['trade_date'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_transaction_id'), 'ibkr_activity_flows', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_ibkr_activity_flows_user_id'), 'ibkr_activity_flows', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ibkr_activity_flows_user_id'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_transaction_id'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_trade_date'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_symbol'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_row_hash'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_raw_symbol'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_market'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_import_batch_id'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_id'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_corporate_action_id'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_broker_account_id'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_broker'), table_name='ibkr_activity_flows')
    op.drop_index(op.f('ix_ibkr_activity_flows_activity_type'), table_name='ibkr_activity_flows')
    op.drop_table('ibkr_activity_flows')
    op.drop_index('uix_broker_flow_user_hash_unassigned', table_name='broker_fund_flows', postgresql_where=sa.text('broker_account_id IS NULL'))
    op.drop_index(op.f('ix_broker_fund_flows_user_id'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_transaction_id'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_trade_date'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_serial_number'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_security_code'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_row_hash'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_import_batch_id'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_id'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_corporate_action_id'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_cash_event_id'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_business_name'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_broker_account_id'), table_name='broker_fund_flows')
    op.drop_index(op.f('ix_broker_fund_flows_broker'), table_name='broker_fund_flows')
    op.drop_table('broker_fund_flows')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_symbol'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_market'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_linked_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_import_batch_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_broker_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reconciliation_snapshots_user_id'), table_name='reconciliation_snapshots')
    op.drop_index(op.f('ix_reconciliation_snapshots_status'), table_name='reconciliation_snapshots')
    op.drop_index(op.f('ix_reconciliation_snapshots_snapshot_date'), table_name='reconciliation_snapshots')
    op.drop_index(op.f('ix_reconciliation_snapshots_import_batch_id'), table_name='reconciliation_snapshots')
    op.drop_index(op.f('ix_reconciliation_snapshots_id'), table_name='reconciliation_snapshots')
    op.drop_index(op.f('ix_reconciliation_snapshots_broker_account_id'), table_name='reconciliation_snapshots')
    op.drop_table('reconciliation_snapshots')
    op.drop_index(op.f('ix_corporate_actions_user_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_symbol'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_market'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_import_batch_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_ex_date'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_broker_account_id'), table_name='corporate_actions')
    op.drop_index(op.f('ix_corporate_actions_action_type'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_import_batches_user_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_status'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_source_type'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_source_sha256'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_broker_account_id'), table_name='import_batches')
    op.drop_index(op.f('ix_import_batches_broker'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_holdings_user_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_symbol'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_market'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_broker_account_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_cash_events_user_id'), table_name='cash_events')
    op.drop_index(op.f('ix_cash_events_id'), table_name='cash_events')
    op.drop_index(op.f('ix_cash_events_event_type'), table_name='cash_events')
    op.drop_index(op.f('ix_cash_events_event_date'), table_name='cash_events')
    op.drop_index(op.f('ix_cash_events_currency'), table_name='cash_events')
    op.drop_index(op.f('ix_cash_events_broker_account_id'), table_name='cash_events')
    op.drop_table('cash_events')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_index(op.f('ix_broker_accounts_id'), table_name='broker_accounts')
    op.drop_index(op.f('ix_broker_accounts_broker'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index('uq_background_jobs_active_user_type', table_name='background_jobs', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_background_jobs_user_type', table_name='background_jobs')
    op.drop_index('ix_background_jobs_finished_at', table_name='background_jobs')
    op.drop_index('ix_background_jobs_claim', table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index('ix_auth_sessions_expires_at', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_prices_ts_code'), table_name='security_prices')
    op.drop_index(op.f('ix_security_prices_symbol'), table_name='security_prices')
    op.drop_index(op.f('ix_security_prices_price_date'), table_name='security_prices')
    op.drop_index(op.f('ix_security_prices_market'), table_name='security_prices')
    op.drop_index(op.f('ix_security_prices_id'), table_name='security_prices')
    op.drop_table('security_prices')
    op.drop_index(op.f('ix_exchange_rates_to_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_from_currency'), table_name='exchange_rates')
    op.drop_index(op.f('ix_exchange_rates_effective_date'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
