"""dividend suggestions and security events

Revision ID: 20260801_0006
Revises: 20260801_0005
Create Date: 2026-08-02 01:24:33.952117+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260801_0006'
down_revision: Union[str, None] = '20260801_0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场'),
    sa.Column('event_type', sa.String(length=30), nullable=False, comment='事件类型'),
    sa.Column('event_date', sa.Date(), nullable=False, comment='事件日期'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='数据来源接口'),
    sa.Column('payload', sa.JSON(), nullable=True, comment='类型特有参数（每股金额、解禁数量等）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('EARNINGS_DISCLOSURE', 'DIVIDEND_PLAN', 'SHARE_UNLOCK')", name='ck_security_events_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', 'event_type', 'event_date', name='uq_security_events_identity')
    )
    op.create_index(op.f('ix_security_events_event_date'), 'security_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_security_events_id'), 'security_events', ['id'], unique=False)
    op.create_index(op.f('ix_security_events_symbol'), 'security_events', ['symbol'], unique=False)
    op.create_table('corporate_action_suggestions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_account_id', sa.Integer(), nullable=True, comment='登记日权益归属账户；NULL=合并口径（归属不可拆）'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='资产名称'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场'),
    sa.Column('action_type', sa.String(length=20), nullable=False, comment='CASH_DIVIDEND / STOCK_DIVIDEND'),
    sa.Column('ann_date', sa.Date(), nullable=True, comment='公告日'),
    sa.Column('record_date', sa.Date(), nullable=True, comment='股权登记日'),
    sa.Column('ex_date', sa.Date(), nullable=False, comment='除权除息日'),
    sa.Column('pay_date', sa.Date(), nullable=True, comment='派息日'),
    sa.Column('currency', sa.String(length=10), server_default='CNY', nullable=False),
    sa.Column('cash_div_pre_tax', sa.Numeric(precision=18, scale=8), nullable=True, comment='每股税前派息（cash_div_tax）'),
    sa.Column('cash_div_after_tax', sa.Numeric(precision=18, scale=8), nullable=True, comment='每股税后派息（cash_div）'),
    sa.Column('stk_div_per_share', sa.Numeric(precision=18, scale=8), nullable=True, comment='每股送转合计（stk_div）'),
    sa.Column('record_date_quantity', sa.Numeric(precision=18, scale=8), nullable=True, comment='登记日推算持仓；NULL=推算失败'),
    sa.Column('quantity_basis', sa.String(length=20), nullable=True, comment='per_account / merged / unavailable'),
    sa.Column('estimated_total_dividend', sa.Numeric(precision=18, scale=8), nullable=True, comment='税前推算总额'),
    sa.Column('status', sa.String(length=20), server_default='NEW', nullable=False),
    sa.Column('matched_corporate_action_id', sa.Integer(), nullable=True, comment='判重命中的既有账本记录'),
    sa.Column('created_corporate_action_id', sa.Integer(), nullable=True, comment='接受后创建的账本记录'),
    sa.Column('match_detail', sa.JSON(), nullable=True, comment='判重明细：matched_by / date_gap_days / amount_diff'),
    sa.Column('source', sa.String(length=30), server_default='tushare-dividend', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action_type IN ('CASH_DIVIDEND', 'STOCK_DIVIDEND')", name='ck_ca_suggestions_action_type'),
    sa.CheckConstraint("status IN ('NEW', 'MATCHED', 'ACCEPTED', 'IGNORED')", name='ck_ca_suggestions_status'),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_corporate_action_id'], ['corporate_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['matched_corporate_action_id'], ['corporate_actions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'market', 'action_type', 'ex_date', 'broker_account_id', name='uq_ca_suggestions_identity', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_corporate_action_suggestions_broker_account_id'), 'corporate_action_suggestions', ['broker_account_id'], unique=False)
    op.create_index(op.f('ix_corporate_action_suggestions_id'), 'corporate_action_suggestions', ['id'], unique=False)
    op.create_index(op.f('ix_corporate_action_suggestions_status'), 'corporate_action_suggestions', ['status'], unique=False)
    op.create_index(op.f('ix_corporate_action_suggestions_symbol'), 'corporate_action_suggestions', ['symbol'], unique=False)
    op.create_index(op.f('ix_corporate_action_suggestions_user_id'), 'corporate_action_suggestions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_corporate_action_suggestions_user_id'), table_name='corporate_action_suggestions')
    op.drop_index(op.f('ix_corporate_action_suggestions_symbol'), table_name='corporate_action_suggestions')
    op.drop_index(op.f('ix_corporate_action_suggestions_status'), table_name='corporate_action_suggestions')
    op.drop_index(op.f('ix_corporate_action_suggestions_id'), table_name='corporate_action_suggestions')
    op.drop_index(op.f('ix_corporate_action_suggestions_broker_account_id'), table_name='corporate_action_suggestions')
    op.drop_table('corporate_action_suggestions')
    op.drop_index(op.f('ix_security_events_symbol'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_id'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_date'), table_name='security_events')
    op.drop_table('security_events')
    # ### end Alembic commands ###
