"""excluded securities

Revision ID: 20260729_0002
Revises: 20260728_0001
Create Date: 2026-07-29 03:18:00.279990+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260729_0002'
down_revision: Union[str, None] = '20260728_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excluded_securities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'market', name='uq_excluded_securities_key')
    )
    op.create_index(op.f('ix_excluded_securities_id'), 'excluded_securities', ['id'], unique=False)
    op.create_index(op.f('ix_excluded_securities_user_id'), 'excluded_securities', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_excluded_securities_user_id'), table_name='excluded_securities')
    op.drop_index(op.f('ix_excluded_securities_id'), table_name='excluded_securities')
    op.drop_table('excluded_securities')
    # ### end Alembic commands ###
