"""watchlist_items：观察清单用户域表

Revision ID: 20260813_0013
Revises: 20260807_0012
Create Date: 2026-08-13 08:58:46.169020+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '20260813_0013'
down_revision: Union[str, None] = '20260807_0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='股票代码'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='市场'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='资产名称（可选，便于列表辨认）'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='观察理由一句话（正式论点见 security_theses）'),
    sa.Column('current_price', sa.Numeric(precision=20, scale=8), nullable=True, comment='最近刷新价（与 Holding 同语义）'),
    sa.Column('price_updated_at', sa.DateTime(timezone=True), nullable=True, comment='价格刷新时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', 'market', name='uq_watchlist_user_symbol')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_symbol'), 'watchlist_items', ['symbol'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_symbol'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    # ### end Alembic commands ###
