import { expect, test } from '@playwright/test'
import { loginThroughApi, mockHoldingsPage, setAuthenticatedSession } from './helpers'

test('desktop width preference survives routes and narrow drawer keyboard actions', async ({
  page,
  request
}) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await setAuthenticatedSession(page, await loginThroughApi(request))
  await mockHoldingsPage(page)
  await page.goto('/holdings')
  const main = page.locator('.app-main')
  const sidebar = page.locator('.desktop-sidebar')
  await expect(page.locator('.app-header')).toHaveCount(0)
  await expect(sidebar).toBeVisible()
  await expect(sidebar).toHaveCSS('width', '208px')
  // 等正文展开动画结束后记录基准宽度，避免采到中间帧。
  await expect.poll(async () => (await main.boundingBox())?.x).toBe(208)
  const expanded = await main.boundingBox()
  const collapse = page.getByRole('button', { name: '收起导航' })
  await collapse.focus()
  await collapse.press('Enter')
  await expect(sidebar).toHaveCSS('width', '56px')
  await expect(sidebar.getByRole('link', { name: '当前持仓', exact: true })).toBeVisible()
  await expect.poll(async () => (await main.boundingBox())!.width - expanded!.width).toBe(152)
  await expect(page.getByRole('button', { name: '展开导航' })).toBeFocused()
  await page.reload()
  await expect(page.getByRole('heading', { name: '当前持仓', exact: true })).toBeVisible()
  await expect(sidebar).toHaveCSS('width', '56px')

  await page.setViewportSize({ width: 393, height: 852 })
  const open = sidebar.getByRole('button', { name: '展开导航' })
  await expect(page.locator('.n-drawer')).toHaveCount(0)
  await open.focus()
  await open.press('Enter')
  await expect(page.getByRole('dialog', { name: '应用导航' })).toBeVisible()
  const drawer = page.getByRole('dialog', { name: '应用导航' })
  const navigation = drawer.getByRole('navigation', { name: '主导航' })
  await expect(navigation.getByRole('link', { name: '雪球观点', exact: true })).toHaveCount(0)
  await expect(navigation.getByRole('link')).toHaveCount(9)
  await expect.poll(() => drawer.evaluate((el) => el.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.locator('.n-drawer')).toHaveCount(0)
  await expect(open).toBeFocused()
  await open.press('Enter')
  await navigation.getByRole('link', { name: '当前持仓', exact: true }).click()
  await expect(page.locator('.n-drawer')).toHaveCount(0)
  await expect(open).toBeFocused()
  await open.press('Enter')
  await drawer.getByRole('button', { name: '设置', exact: true }).click()
  await page.getByRole('button', { name: '修改密码', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '修改密码' })
  await expect(dialog).toBeVisible()
  await expect(page.locator('.n-drawer')).toHaveCount(0)
  await expect
    .poll(() => dialog.evaluate((element) => element.contains(document.activeElement)))
    .toBe(true)
  await page.keyboard.press('Tab')
  await expect
    .poll(() => dialog.evaluate((element) => element.contains(document.activeElement)))
    .toBe(true)
  await page.keyboard.press('Escape')
  await expect(dialog).toBeHidden()
  await page.setViewportSize({ width: 1440, height: 900 })
  await expect(sidebar).toHaveCSS('width', '56px')
  await page.getByRole('button', { name: '展开导航' }).click()
  await expect(sidebar).toHaveCSS('width', '208px')
  await page.goto('/transactions')
  await expect(sidebar).toHaveCSS('width', '208px')
})

test('navigation links support new tabs and administrator entries follow the session', async ({
  page,
  request
}) => {
  await page.setViewportSize({ width: 1440, height: 900 })
  await setAuthenticatedSession(page, await loginThroughApi(request))
  await mockHoldingsPage(page)
  await page.goto('/holdings')
  const navigation = page.getByRole('navigation', { name: '主导航' })
  await expect(navigation.getByRole('link', { name: '雪球观点', exact: true })).toHaveCount(0)
  await expect(navigation.getByRole('link')).toHaveCount(9)
  await expect(navigation.getByRole('link', { name: '用户管理' })).toHaveCount(0)
  const transactions = navigation.getByRole('link', { name: '交易记录', exact: true })
  await expect(transactions).toHaveAttribute('href', '/transactions')
  const [tab] = await Promise.all([
    page.context().waitForEvent('page'),
    transactions.click({ modifiers: ['Control'] })
  ])
  await expect(tab).toHaveURL(/\/transactions$/)
  await expect(page).toHaveURL(/\/holdings$/)
  await tab.close()
  const account = page.getByRole('button', { name: '设置', exact: true })
  await account.focus()
  await account.press('Space')
  await expect(account).toHaveAttribute('aria-expanded', 'true')
  const settings = page.getByRole('group', { name: '设置', exact: true })
  await expect(settings).toBeVisible()
  await expect(settings).toContainText('demo')
  await page.keyboard.press('Tab')
  await expect(settings.getByRole('button', { name: /^外观：/ })).toBeFocused()
  await page.keyboard.press('Shift+Tab')
  await expect(account).toBeFocused()
  await account.press('Escape')
  await expect(account).toHaveAttribute('aria-expanded', 'false')
  await expect(account).toBeFocused()
  await account.press('Enter')
  await expect(account).toHaveAttribute('aria-expanded', 'true')
  await account.press('ArrowDown')
  await expect(settings.getByRole('button', { name: /^外观：/ })).toBeFocused()
  await page.keyboard.press('Tab')
  await expect(settings.getByRole('button', { name: '修改密码', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  const password = page.getByRole('dialog', { name: '修改密码' })
  await expect(password).toBeVisible()
  await expect
    .poll(() => password.evaluate((element) => element.contains(document.activeElement)))
    .toBe(true)
  await page.keyboard.press('Escape')
  await expect(password).toBeHidden()
  await expect(account).toBeFocused()
  const response = await request.post('http://127.0.0.1:18000/api/auth/token', {
    data: { username: 'admin', password: 'e2e-admin-password' }
  })
  expect(response.ok()).toBeTruthy()
  await setAuthenticatedSession(page, (await response.json()).access_token)
  await page.reload()
  await expect(navigation.getByRole('link')).toHaveCount(13)
  await navigation.getByRole('link', { name: '用户管理', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/users$/)
  await expect(navigation.getByRole('link', { name: '用户管理', exact: true })).toHaveAttribute(
    'aria-current',
    'page'
  )
})
